/// <reference types="node" />
// Required because @types/node is not auto-included for this project (pnpm-symlinked
// typeRoots); scoped to this test file, which reads the spec snapshot as its fixture.

/**
 * Conformance against the wire spec: the allowlist block (§4), the command summary table (§6.0)
 * and the wire-field dictionary (§7), so drift between the doc and this package fails loudly.
 *
 * The fixture is `spec-snapshot.json`, NOT `docs/current/wire-protocol.md`. This test used to
 * read the spec directly, and because `docs/` is gitignored (`.gitignore:11`) it failed at
 * collection time in every fresh worktree with `ENOENT ... wire-protocol.md`, turning `pnpm test`
 * red for a reason unrelated to whatever the developer had changed. A test may not depend on an
 * ignored file, so the spec's three machine-checkable tables are snapshotted into the package by
 * `scripts/snapshot-wire-spec.mjs` and committed beside this file.
 *
 * That splits the original guard in two, and both halves still run:
 *   - snapshot vs TypeScript is HERE, and runs everywhere, including a fresh worktree. It is the
 *     half that catches someone editing `allowlist.ts`, `messages.ts` or `fields.ts`;
 *   - spec vs snapshot is `node packages/protocol/scripts/snapshot-wire-spec.mjs --check`, run by
 *     `scripts/verify.mjs`. It needs the doc, so it lives outside the test suite and reports
 *     out loud when `docs/` is absent rather than passing quietly.
 *
 * After editing the spec, regenerate the snapshot:
 *
 *   node packages/protocol/scripts/snapshot-wire-spec.mjs
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { isReplyCommand, REPLY_COMMANDS } from '../allowlist.js';
import { WIRE_FIELD_TYPES, type WireFieldKind } from './fields.js';
import { isWireCommand, WIRE_COMMANDS } from './messages.js';

interface SpecSnapshot {
    readonly source: string;
    readonly regenerate: string;
    readonly replyAllowlist: readonly string[];
    readonly commands: readonly { readonly command: string; readonly mode: 'R/R' | 'F&F' }[];
    readonly fields: Readonly<Record<string, WireFieldKind>>;
}

const SNAPSHOT = JSON.parse(
    readFileSync(new URL('./spec-snapshot.json', import.meta.url), 'utf8')
) as SpecSnapshot;

describe('spec snapshot', () => {
    // The floors the test used to apply to its live parse of the spec. They belong here too: a
    // snapshot regenerated by a parser that silently matched nothing would turn every assertion
    // below into a tautology, and an empty fixture passing is exactly the failure this file is
    // meant not to have.
    it('is substantial, so the assertions below are not vacuous', () => {
        expect(SNAPSHOT.replyAllowlist.length).toBeGreaterThan(50);
        expect(SNAPSHOT.commands.length).toBeGreaterThan(60);
        expect(Object.keys(SNAPSHOT.fields).length).toBeGreaterThan(60);
    });

    it('records where it came from and how to regenerate it', () => {
        expect(SNAPSHOT.source).toBe('docs/current/wire-protocol.md');
        expect(SNAPSHOT.regenerate).toContain('snapshot-wire-spec.mjs');
    });
});

describe('reply allowlist (§4)', () => {
    it('matches the spec set exactly', () => {
        expect([...REPLY_COMMANDS].sort()).toEqual([...SNAPSHOT.replyAllowlist].sort());
    });

    it('recognizes every allowlisted name through isReplyCommand', () => {
        for (const command of SNAPSHOT.replyAllowlist) expect(isReplyCommand(command)).toBe(true);
        expect(isReplyCommand('start')).toBe(false);
        expect(isReplyCommand('nonsense')).toBe(false);
    });
});

describe('command summary table (§6.0)', () => {
    it('covers every documented command', () => {
        expect([...new Set(SNAPSHOT.commands.map((row) => row.command))].sort()).toEqual([...WIRE_COMMANDS].sort());
    });

    it('agrees with the allowlist on request/response vs fire-and-forget', () => {
        for (const row of SNAPSHOT.commands) {
            expect(isWireCommand(row.command)).toBe(true);
            expect(isReplyCommand(row.command)).toBe(row.mode === 'R/R');
        }
    });
});

describe('wire-field dictionary (§7)', () => {
    it('lists the same keys as the decoder knows', () => {
        expect(Object.keys(SNAPSHOT.fields).sort()).toEqual(Object.keys(WIRE_FIELD_TYPES).sort());
    });

    it('agrees on every field type', () => {
        for (const [field, kind] of Object.entries(SNAPSHOT.fields)) {
            expect((WIRE_FIELD_TYPES as Record<string, WireFieldKind>)[field]).toBe(kind);
        }
    });
});
